// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated by: qmk painter-convert-font-image --input FiraCodeNerdFontMono-Regular-24.png --output . --no-ascii False --unicode-glyphs  --format mono4 --no-rle False

#pragma once

#include <qp.h>

extern const uint32_t font_FiraCodeNerdFontMono_Regular_24_length;
extern const uint8_t  font_FiraCodeNerdFontMono_Regular_24[6792];
