// Copyright 2026 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | pal16
//    output | cravingpixels
//    input  | sleeping_snorlax_120x96.gif

#pragma once

#include <qp.h>

extern const uint32_t gfx_sleeping_snorlax_120x96_length;
extern const uint8_t  gfx_sleeping_snorlax_120x96[14264];
